### PR TITLE
Introduce default var bitbucket_download_directory

### PR DESCRIPTION
**Pull request by mrtwnklr**
**Changes:**

Introduce default var `bitbucket_download_directory` to support overriding the download path at role usage level.

### CODE REVIEW

**Comment by hswong3i** [comment]
Why don't just simply customize your `bitbucket_download` in case don't like the `~/.ansible/tmp`?

Sorry for asking this because I keep synchronize all Ansible Roles under https://github.com/alvistack with similar setting, in case accepting this PR I need to ensure also benefit for other else use cases.

**Comment by mrtwnklr** [comment]
Thanks for your question. I thought about customizing `bitbucket_download` first, but it would be a maintenance nightmare for me to take care for the three components (`url`, `dest` and `checksum`) of each version.
By just extracting the download path I have no additional effort in the future when you update `_bitbucket_download` (and the other `_***_download` vars) for new versions.

But maybe I misunderstood your question?

**Comment by mrtwnklr** [comment]
After taking another look at the code I realize, that it would be cleaner to introduce three vars: `bitbucket_download_directory`, `mysql_jdbc_download_directory` and `postgresql_jdbc_download_directory`.

When you agree to this kind of change I would extend the pull request.

**Comment by hswong3i** [comment]
From my point of view, I hope to fetch the `remote_tmp` variable (see https://github.com/ansible/ansible/blob/devel/examples/ansible.cfg#L17) from playbook/task therefore you just need to set it up in a single place.

**Comment by mrtwnklr** [comment]
I understand. But changing `remote_tmp` won't meet my requirements.

I am using your role(s) to provision several vagrant boxes. I don't want to download the atlassian files over and over again after destroying and re-provisioning vagrant boxes (for development and testing purposes, sometimes multiple times per day).

The introduced var `bitbucket_download_directory` enables me to store the downloaded files (and only these) outside of the vagrant box. So these files can be reused later. Using and changing `remote_tmp` would store much more files in my "caching" directory.

**Comment by hswong3i** [comment]
@mrtwnklr First of all let's review the initial requirement for download assets into `~/.ansible/tmp/` with current logic:
- **We need a way to handle initial install or upgrade.** If the target file assets not exists, we assume for a new install or upgrade, so purge existing data and do the extract/install/compile/etc
- **We need a way to skip duplicated install.** If the target file assets already exists with expected checksum, we assume initial installation done so skip it
- **We need a way to manually trigger reinstall.** Similar as case above, just simply remove the existing file assets and rerun the role/playbook will trigger the reinstallation

Therefore we need to download the file assets from network. If you reuse the cache folder across multiple newly-cleanly-started vagrant boxes, the remaining boxes will simply skip the installation as file assets already exists...

P.S. From the other point of view, with vagrant you could use sync folder + rsync (see https://www.vagrantup.com/docs/synced-folders/rsync.html). In this case you could always sync the `~/.ansible/tmp/` if you truly understand this role's logic.

**Comment by mrtwnklr** [comment]
Thank you for your fast response. I understand the current logic. I did not do a deep dive into the role before. Now I see that my change will not meet my requirements in the long run. I have to think about it.

**Comment by hswong3i** [comment]
Thank you for your understanding. Let's reopen this PR again, e.g. if we could find a way to centralize the target path into `remote_tmp`.

**Pull request closed without merging**
